name: Full CI - Frontend & Backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  flutter-build:
    name: Build & Test Flutter App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'

      - name: Install dependencies
        run: |
          cd gestion_vente_app
          flutter pub get

      - name: Run tests
        run: |
          cd gestion_vente_app
          flutter test

  backend-build:
    name: Build Backend
    runs-on: ubuntu-latest
    needs: flutter-build  # attend que le front soit fini (optionnel)

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build backend with Maven
        run: |
          cd backend
          ./mvnw clean install || mvn clean install
